// PLEASE DO NOT EDIT THIS FILE, 
// IF YOU WANT ADD ANY CODE CREATE NEW JS INTO client-custom 
 import axios from 'axios'; 
 window.axios = axios; 
 
 window.axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';
import "./client-custom/assetsNode.js";
import "./client-custom/confirm.js";
import "./client-custom/safeForm.js";
import "./client-custom/windowLoader.js";
import "../views/segments/preloader/PreloaderCircle/PreloaderCircle.js";
import "../views/segments/header/ParallaxHeaderPin/ParallaxHeaderPin.js";
import "../views/segments/group/SubGroupsGrid/SubGroupsGrid.js";
import "../views/segments/posts_page/SimplePostList/SimplePostList.js";
import "../views/segments/gallery/GallaryGrid/GallaryGrid.js";
import "../views/segments/galleries/GridGallery/GridGallery.js";
