// PLEASE DO NOT EDIT THIS FILE, 
// IF YOU WANT ADD ANY CODE CREATE NEW JS INTO client-custom 
 import axios from 'axios'; 
 window.axios = axios; 
 
 window.axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';
import "./client-custom/assetsNode.js";
import "./client-custom/confirm.js";
import "./client-custom/customerActions.js";
import "./client-custom/login.js";
import "./client-custom/safeForm.js";
import "./client-custom/tabControll.js";
import "./client-custom/windowLoader.js";
import "../views/segments/preloader/PreloaderCircle/PreloaderCircle.js";
import "../views/segments/menu/RecetMenu/RecetMenu.js";
import "../views/segments/slider/SliderSimple/SliderSimple.js";
import "../views/segments/index/CounterGrid/CounterGrid.js";
import "../views/segments/categories/CategoriesFavImageLinks/CategoriesFavImageLinks.js";
import "../views/segments/menu/AplMenu/AplMenu.js";
import "../views/segments/products_page/ProductGridSidebar/ProductGridSidebar.js";
import "../views/segments/product/ProductKaren/ProductKaren.js";
import "../views/segments/products_page/ProductGridSidebar/ProductGridSidebar.js";
import "../views/segments/gallery/GallaryGrid/GallaryGrid.js";
